---
version: 1.5.3-2
slug: porcupine
name: porcupine v4.0.0
description: RK3588 porcupine 4 using the Wyoming protocol
url: https://github.com/OldWancn/hassio-addons/tree/main/porcupine
ingress: false
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
map:
  - share:ro
options:
  sensitivity: 0.5
  debug_logging: false
schema:
  sensitivity: float
  access_key: str
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
